import React, { createContext, useContext, useState, useEffect } from 'react';
import { geminiService } from '../services/geminiService';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  translateText: (text: string) => Promise<string>;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'wifi_settings': 'Wi-Fi Settings',
    'main_wifi': 'Main Wi-Fi',
    'guest_wifi_settings': 'Guest Wi-Fi Settings',
    'security': 'Security',
    'encryption': 'Encryption',
    'channel_selection': 'Channel Selection',
    'hide_ssid': 'Hide SSID',
    'wpa2_psk_aes': 'WPA2-PSK (AES)',
    'wpa3_sae': 'WPA3-SAE',
    'wpa_wpa2_mixed': 'WPA/WPA2 Mixed',
    'settings_updated': 'Settings updated successfully',
    'update_failed': 'Failed to update settings',
    'dashboard': 'Dashboard',
    'devices': 'Devices',
    'analytics': 'Analytics',
    'optimizer': 'Optimizer',
    'profiles': 'Profiles',
    'settings': 'Settings',
    'help': 'Help Center',
    'logout': 'Logout',
    'network_overview': 'Network Overview',
    'real_time_status': 'Real-time status of your NetGuard Pro router',
    'reboot_router': 'Reboot Router',
    'system_online': 'System Online',
    'download': 'Download',
    'upload': 'Upload',
    'active': 'Active',
    'uptime': 'Uptime',
    'current_speed': 'Current speed',
    'connected_now': 'Connected now',
    'system_stability': 'System stability',
    'real_time_traffic': 'Real-time Traffic',
    'system_performance': 'System Performance',
    'cpu_load': 'CPU Load',
    'ram_usage': 'RAM Usage',
    'quick_actions': 'Quick Actions',
    'guest_wifi': 'Guest Wi-Fi',
    'security_scan': 'Security Scan',
    'scan_complete': 'Scan Complete',
    'no_threats': 'No threats detected. Your network is secure.',
    'weekly_consumption': 'Weekly Consumption',
    'data_usage_gb': 'Data usage in GB',
    'quick_stats': 'Quick Stats',
    'total_download': 'Total Download',
    'total_upload': 'Total Upload',
    'peak_usage': 'Peak Usage',
    'network_health': 'Network Health',
    'connection_logs': 'Connection Logs',
    'recent_events': 'Recent network events',
    'router_settings': 'Router Settings',
    'configure_wifi': 'Configure your Wi-Fi and network security parameters',
    'wifi_config': 'Wi-Fi Configuration',
    'ssid': 'SSID (Network Name)',
    'security_mode': 'Security Mode',
    'wifi_password': 'Wi-Fi Password',
    'save_changes': 'Save Changes',
    'guest_network': 'Guest Network',
    'enable_guest': 'Enable Guest Wi-Fi',
    'guest_ssid': 'Guest SSID',
    'network_optimization': 'Network Optimization',
    'channel_optimizer': 'Channel Optimizer',
    'current_channel': 'Current Channel',
    'optimize_now': 'Optimize Now',
    'parental_controls': 'Parental Controls',
    'access_schedule': 'Access Schedule',
    'content_filter': 'Content Filter',
    'dns_settings': 'DNS Settings',
    'primary_dns': 'Primary DNS',
    'secondary_dns': 'Secondary DNS',
    'custom_dns': 'Custom DNS',
    'usage_by_app': 'Usage by Application',
    'usage_by_content': 'Usage by Content Type',
    'month': 'Month',
    'week': 'Week',
    'day': 'Day',
    'timeline': 'Timeline',
    'app_consumption': 'App Consumption',
    'device_consumption': 'Device Consumption',
    'device_management': 'Device Management',
    'manage_secure_devices': 'Manage and secure {count} devices on your network',
    'search_placeholder': 'Search by name or IP...',
    'export': 'Export',
    'total': 'Total',
    'online': 'Online',
    'offline': 'Offline',
    'all_devices': 'All Devices',
    'unblock_all': 'Unblock All',
    'device': 'Device',
    'status': 'Status',
    'signal': 'Signal',
    'ip_mac': 'IP / MAC Address',
    'speed': 'Speed',
    'actions': 'Actions',
    'unblock': 'Unblock',
    'block': 'Block',
    'no_devices_found': 'No devices found',
    'no_blocked_devices': "Great! You haven't blocked any devices yet.",
    'try_searching_different': 'Try searching for a different name or IP address.',
    'help_center': 'Help Center',
    'how_can_we_help': 'How can we help you today?',
    'back_to_topics': 'Back to Topics',
    'search_help_placeholder': 'Search for a feature or issue...',
    'still_need_help': 'Still need help?',
    'contact_support': 'Contact Support',
    'dashboard_overview': 'Dashboard Overview',
    'understand_stats': 'Understand your real-time network statistics.',
    'wifi_optimizer': 'Wi-Fi Optimizer',
    'improve_signal': 'How to improve your Wi-Fi signal stability.',
    'security_shield': 'Security Shield',
    'learn_protection': 'Learn about the military-grade protection.',
    'control_access': 'Control who accesses your network.',
    'configure_dns_help': 'Configure custom DNS servers for your network.',
    'ai_translation': 'AI Translation',
    'ai_translation_help': 'Learn how AI helps translate the app.',
    'advanced_analytics': 'Advanced Analytics',
    'router_connectivity': 'Router Connectivity',
    'router_connectivity_help': 'Connect to your router using different protocols.',
    'detailed_consumption_help': 'Track detailed consumption history and app usage.',
    'mobile_data': 'Mobile Data',
    'cellular': 'Cellular',
    'wifi': 'Wi-Fi',
    'connection_type': 'Connection Type',
    'data_plan': 'Data Plan',
    'used': 'Used',
    'remaining': 'Remaining',
    'days_left': 'Days Left',
    'signal_strength': 'Signal Strength',
    'operator': 'Operator',
    'roaming': 'Roaming',
    'set_data_limit': 'Set Data Limit',
    'master_supervisor_mode': 'Master Supervisor Mode',
    'global_infrastructure': 'Global Network Infrastructure Overview',
    'exit_master_mode': 'Exit Master Mode',
    'total_connections': 'Total Connections',
    'unique_brands': 'Unique Brands',
    'system_status': 'System Status',
    'optimal': 'Optimal',
    'connected_router_history': 'Connected Router History',
    'verified': 'Verified',
    'total_routers': 'Total Routers',
    'active_gateway': 'Active Gateway',
    'total_traffic': 'Total Traffic',
    'session_logs': 'Session Logs',
    'entries': 'Entries',
    'live': 'Live',
    'speed_test': 'Speed Test',
    'testing': 'Testing...',
    'rebooting': 'Rebooting...',
    'back_to_login': 'Back to Login',
    'no_router_connected': 'No Router Connected',
    'connect_instruction': 'Please login with your router credentials to access the admin panel.',
    'parental_control_title': 'Parental Control & Content Filtering',
    'under_development': 'Under Development',
    'content_filtering_desc': 'Block malicious websites, adult content, and set browsing schedules for specific devices. This feature is currently being optimized for your router model.',
    'configure': 'Configure',
    'close': 'Close',
    'no_logs_found': 'No session logs found.',
    'success': 'Success',
    'secure_gateway': 'Secure Gateway Management',
    'preview_mode': 'Preview Mode: Use',
    'connection_protocol': 'Connection Protocol',
    'router_address': 'Router Address',
    'username': 'Username',
    'password': 'Password',
    'remember_password': 'Remember Password',
    'forgot': 'Forgot?',
    'sign_in': 'Sign In',
    'biometric_login': 'Biometric Login',
    'ssh_desc': 'Paramiko (SSH) for CLI access',
    'api_desc': 'Requests (HTTP) for REST API',
    'web_desc': 'Selenium (Web) for scraping dashboard',
    'auth_error_auth': 'Failed to authorize with router. Check credentials.',
    'auth_error_conn': 'Failed to connect to router. Check address and network.',
    'auth_error_brute': 'Too many failed attempts. Please try again later.',
    'check_home_wifi': 'Please make sure you are connected to your home Wi-Fi.',
    'of': 'of',
    'gb_of_gb': '{used} GB of {limit} GB',
    'download_mbps': 'Download',
    'upload_mbps': 'Upload',
    'none': 'None',
    'router_profiles': 'Router Profiles',
    'manage_gateways': 'Manage encrypted credentials for multiple gateways',
    'add_router': 'Add New Router',
    'no_profiles': 'No Profiles Saved',
    'add_first_router': 'Add your first router to start monitoring',
    'profile_name': 'Profile Name',
    'router_ip': 'Router IP',
    'save_profile': 'Save Profile',
    'cancel': 'Cancel',
    'connect_now': 'Connect Now',
    'aes_encrypted': 'AES-256 Encrypted',
    'show_password': 'Show Password',
    'hide_password': 'Hide Password',
    'discovery_mode': 'Discovery Mode',
    'searching_router': 'Searching for local router...',
    'router_found': 'Router found at {ip}',
    'router_not_found': 'No router found automatically. Please enter IP manually.',
    'dark_mode': 'Dark Mode',
    'light_mode': 'Light Mode',
    'joined': 'Joined',
    'left': 'Left',
    'blocked': 'Blocked',
    'unblocked': 'Unblocked',
    'language_region': 'Language & Region',
    'lang_change_desc': 'Changing language will update the interface and AI analysis.',
    'scanning': 'Scanning...',
    'optimizer_desc': 'Automatically scan and switch to the least congested Wi-Fi channel.',
    'time_limit_desc': 'Set time limits for devices',
    'block_restricted_desc': 'Block restricted websites',
    'automatic': 'Automatic',
    'manual': 'Manual',
    'saving': 'Saving...',
    'confirm_reboot': 'Are you sure you want to reboot the router? This will temporarily disconnect all devices.',
    'consumption_history': 'Consumption History',
    'daily': 'Daily',
    'usage_by_application': 'Usage by Application',
    'content_distribution': 'Content Distribution',
    'device_control': 'Device Control',
    'unblock_device': 'Unblock Device',
    'block_device': 'Block Device',
    'limit_usage': 'Limit Usage',
    'profile_placeholder': 'Home Router, Office, etc.',
    'pass_placeholder': 'Router Admin Password',
    'auto_detect': 'Auto-Detect',
    'security_shield_active': 'Security Shield Active',
    'threats_detected': 'Threats Detected',
    'scanning_for_threats': 'Scanning for threats...',
    'brute_force_detected': 'Brute Force Attack Detected',
    'mitm_detected': 'Man-in-the-Middle Attack Detected',
    'evil_twin_detected': 'Evil Twin Network Detected',
    'speed_test_result': 'Speed Test Result',
    'ping': 'Ping',
    'ms': 'ms',
    'mbps': 'Mbps',
    'auto_detect_success': 'Router detected successfully',
    'auto_detect_failed': 'Auto-detection failed'
  },
  ar: {
    'wifi_settings': 'إعدادات الواي فاي',
    'main_wifi': 'الواي فاي الرئيسي',
    'guest_wifi_settings': 'إعدادات واي فاي الضيوف',
    'security': 'الأمان',
    'encryption': 'التشفير',
    'channel_selection': 'اختيار القناة',
    'hide_ssid': 'إخفاء اسم الشبكة',
    'wpa2_psk_aes': 'WPA2-PSK (AES)',
    'wpa3_sae': 'WPA3-SAE',
    'wpa_wpa2_mixed': 'WPA/WPA2 مختلط',
    'settings_updated': 'تم تحديث الإعدادات بنجاح',
    'update_failed': 'فشل تحديث الإعدادات',
    'dashboard': 'لوحة التحكم',
    'devices': 'الأجهزة',
    'analytics': 'التحليلات',
    'optimizer': 'المحسن',
    'profiles': 'الملفات الشخصية',
    'settings': 'الإعدادات',
    'help': 'مركز المساعدة',
    'logout': 'تسجيل الخروج',
    'network_overview': 'نظرة عامة على الشبكة',
    'real_time_status': 'حالة راوتر NetGuard Pro في الوقت الفعلي',
    'reboot_router': 'إعادة تشغيل الراوتر',
    'system_online': 'النظام متصل',
    'download': 'تحميل',
    'upload': 'رفع',
    'active': 'نشط',
    'uptime': 'وقت التشغيل',
    'current_speed': 'السرعة الحالية',
    'connected_now': 'متصل الآن',
    'system_stability': 'استقرار النظام',
    'real_time_traffic': 'حركة المرور في الوقت الفعلي',
    'system_performance': 'أداء النظام',
    'cpu_load': 'حمولة المعالج',
    'ram_usage': 'استهلاك الذاكرة',
    'quick_actions': 'إجراءات سريعة',
    'guest_wifi': 'واي فاي الضيوف',
    'security_scan': 'فحص أمني',
    'scan_complete': 'اكتمل الفحص',
    'no_threats': 'لم يتم اكتشاف تهديدات. شبكتك آمنة.',
    'weekly_consumption': 'الاستهلاك الأسبوعي',
    'data_usage_gb': 'استهلاك البيانات بالجيجابايت',
    'quick_stats': 'إحصائيات سريعة',
    'total_download': 'إجمالي التحميل',
    'total_upload': 'إجمالي الرفع',
    'peak_usage': 'ذروة الاستهلاك',
    'network_health': 'صحة الشبكة',
    'connection_logs': 'سجلات الاتصال',
    'recent_events': 'أحداث الشبكة الأخيرة',
    'router_settings': 'إعدادات الراوتر',
    'configure_wifi': 'تكوين الواي فاي ومعايير أمن الشبكة',
    'wifi_config': 'تكوين الواي فاي',
    'ssid': 'اسم الشبكة (SSID)',
    'security_mode': 'وضع الأمان',
    'wifi_password': 'كلمة مرور الواي فاي',
    'save_changes': 'حفظ التغييرات',
    'guest_network': 'شبكة الضيوف',
    'enable_guest': 'تفعيل واي فاي الضيوف',
    'guest_ssid': 'SSID للضيوف',
    'network_optimization': 'تحسين الشبكة',
    'channel_optimizer': 'محسن القنوات',
    'current_channel': 'القناة الحالية',
    'optimize_now': 'تحسين الآن',
    'parental_controls': 'الرقابة الأبوية',
    'access_schedule': 'جدول الوصول',
    'content_filter': 'تصفية المحتوى',
    'dns_settings': 'إعدادات DNS',
    'primary_dns': 'DNS الأساسي',
    'secondary_dns': 'DNS الثانوي',
    'custom_dns': 'DNS مخصص',
    'usage_by_app': 'الاستهلاك حسب التطبيق',
    'usage_by_content': 'الاستهلاك حسب نوع المحتوى',
    'month': 'شهر',
    'week': 'أسبوع',
    'day': 'يوم',
    'timeline': 'الخط الزمني',
    'app_consumption': 'استهلاك التطبيقات',
    'device_consumption': 'استهلاك الأجهزة',
    'device_management': 'إدارة الأجهزة',
    'manage_secure_devices': 'إدارة وتأمين {count} أجهزة في شبكتك',
    'search_placeholder': 'البحث بالاسم أو IP...',
    'export': 'تصدير',
    'total': 'الإجمالي',
    'online': 'متصل',
    'offline': 'غير متصل',
    'all_devices': 'جميع الأجهزة',
    'unblock_all': 'إلغاء حظر الكل',
    'device': 'الجهاز',
    'status': 'الحالة',
    'signal': 'الإشارة',
    'ip_mac': 'عنوان IP / MAC',
    'speed': 'السرعة',
    'actions': 'الإجراءات',
    'unblock': 'إلغاء الحظر',
    'block': 'حظر',
    'no_devices_found': 'لم يتم العثور على أجهزة',
    'no_blocked_devices': 'رائع! لم تقم بحظر أي أجهزة بعد.',
    'try_searching_different': 'حاول البحث عن اسم أو عنوان IP مختلف.',
    'help_center': 'مركز المساعدة',
    'how_can_we_help': 'كيف يمكننا مساعدتك اليوم؟',
    'back_to_topics': 'العودة إلى المواضيع',
    'search_help_placeholder': 'البحث عن ميزة أو مشكلة...',
    'still_need_help': 'هل ما زلت بحاجة للمساعدة؟',
    'contact_support': 'اتصل بالدعم',
    'dashboard_overview': 'نظرة عامة على لوحة التحكم',
    'understand_stats': 'فهم إحصائيات شبكتك في الوقت الفعلي.',
    'wifi_optimizer': 'محسن الواي فاي',
    'improve_signal': 'كيفية تحسين استقرار إشارة الواي فاي.',
    'security_shield': 'درع الأمان',
    'learn_protection': 'تعرف على طبقات الحماية لدينا.',
    'control_access': 'التحكم في من يصل إلى شبكتك.',
    'configure_dns_help': 'تكوين خوادم DNS مخصصة لشبكتك.',
    'ai_translation': 'ترجمة الذكاء الاصطناعي',
    'ai_translation_help': 'تعرف على كيفية مساعدة الذكاء الاصطناعي في ترجمة التطبيق.',
    'advanced_analytics': 'تحليلات متقدمة',
    'router_connectivity': 'اتصال الراوتر',
    'router_connectivity_help': 'الاتصال بالراوتر باستخدام بروتوكولات مختلفة.',
    'detailed_consumption_help': 'تتبع سجل الاستهلاك التفصيلي واستخدام التطبيقات.',
    'mobile_data': 'بيانات الجوال',
    'cellular': 'خلوي',
    'wifi': 'واي فاي',
    'connection_type': 'نوع الاتصال',
    'data_plan': 'باقة البيانات',
    'used': 'مستخدم',
    'remaining': 'متبقي',
    'days_left': 'أيام متبقية',
    'signal_strength': 'قوة الإشارة',
    'operator': 'المشغل',
    'roaming': 'تجوال',
    'set_data_limit': 'تعيين حد البيانات',
    'master_supervisor_mode': 'وضع المشرف الرئيسي',
    'global_infrastructure': 'نظرة عامة على البنية التحتية العالمية للشبكة',
    'exit_master_mode': 'الخروج من الوضع الرئيسي',
    'total_connections': 'إجمالي الاتصالات',
    'unique_brands': 'العلامات التجارية الفريدة',
    'system_status': 'حالة النظام',
    'optimal': 'مثالي',
    'connected_router_history': 'سجل أجهزة الراوتر المتصلة',
    'verified': 'تم التحقق',
    'total_routers': 'إجمالي أجهزة الراوتر',
    'active_gateway': 'البوابة النشطة',
    'total_traffic': 'إجمالي حركة المرور',
    'session_logs': 'سجلات الجلسات',
    'entries': 'مدخلات',
    'live': 'مباشر',
    'speed_test': 'اختبار السرعة',
    'testing': 'جاري الاختبار...',
    'rebooting': 'جاري إعادة التشغيل...',
    'back_to_login': 'العودة لتسجيل الدخول',
    'no_router_connected': 'لا يوجد راوتر متصل',
    'connect_instruction': 'يرجى تسجيل الدخول باستخدام بيانات اعتماد الراوتر للوصول إلى لوحة الإدارة.',
    'parental_control_title': 'الرقابة الأبوية وتصفية المحتوى',
    'under_development': 'قيد التطوير',
    'content_filtering_desc': 'حظر المواقع الضارة، المحتوى البالغ، وتعيين جداول التصفح لأجهزة محددة. هذه الميزة قيد التحسين حالياً لموديل الراوتر الخاص بك.',
    'configure': 'تكوين',
    'close': 'إغلاق',
    'no_logs_found': 'لم يتم العثور على سجلات جلسات.',
    'success': 'نجاح',
    'secure_gateway': 'إدارة البوابة الآمنة',
    'preview_mode': 'وضع المعاينة: استخدم',
    'connection_protocol': 'بروتوكول الاتصال',
    'router_address': 'عنوان الراوتر',
    'username': 'اسم المستخدم',
    'password': 'كلمة المرور',
    'remember_password': 'تذكر كلمة المرور',
    'forgot': 'نسيت؟',
    'sign_in': 'تسجيل الدخول',
    'biometric_login': 'الدخول بالبصمة',
    'ssh_desc': 'Paramiko (SSH) للوصول إلى واجهة الأوامر',
    'api_desc': 'Requests (HTTP) لواجهة برمجة التطبيقات REST',
    'web_desc': 'Selenium (Web) لكشط لوحة التحكم',
    'auth_error_auth': 'فشل التفويض مع الراوتر. تحقق من البيانات.',
    'auth_error_conn': 'فشل الاتصال بالراوتر. تحقق من العنوان والشبكة.',
    'auth_error_brute': 'محاولات كثيرة فاشلة. يرجى المحاولة لاحقاً.',
    'check_home_wifi': 'تأكد من اتصالك بالواي فاي الخاص بالمنزل',
    'of': 'من',
    'gb_of_gb': '{used} جيجابايت من {limit} جيجابايت',
    'download_mbps': 'تحميل',
    'upload_mbps': 'رفع',
    'none': 'لا يوجد',
    'router_profiles': 'ملفات الراوتر',
    'manage_gateways': 'إدارة بيانات الاعتماد المشفرة لعدة بوابات',
    'add_router': 'إضافة راوتر جديد',
    'no_profiles': 'لا توجد ملفات محفوظة',
    'add_first_router': 'أضف أول راوتر لبدء المراقبة',
    'profile_name': 'اسم الملف الشخصي',
    'router_ip': 'عنوان IP للراوتر',
    'save_profile': 'حفظ الملف الشخصي',
    'cancel': 'إلغاء',
    'connect_now': 'اتصل الآن',
    'aes_encrypted': 'مشفر بـ AES-256',
    'show_password': 'إظهار كلمة المرور',
    'hide_password': 'إخفاء كلمة المرور',
    'discovery_mode': 'وضع الاكتشاف',
    'searching_router': 'البحث عن الراوتر المحلي...',
    'router_found': 'تم العثور على راوتر في {ip}',
    'router_not_found': 'لم يتم العثور على راوتر تلقائياً. يرجى إدخال IP يدوياً.',
    'dark_mode': 'الوضع الداكن',
    'light_mode': 'الوضع الفاتح',
    'joined': 'انضم',
    'left': 'غادر',
    'blocked': 'محظور',
    'unblocked': 'غير محظور',
    'optimizer_subtitle': 'تحليل وتقليل ازدحام الشبكة',
    'scanning_spectrum': 'جاري فحص الطيف...',
    'rescan_channels': 'إعادة فحص القنوات',
    'channel_interference': 'تداخل القنوات',
    'recommended': 'موصى به',
    'normal': 'عادي',
    'congested': 'مزدحم',
    'optimization_result': 'نتيجة التحسين',
    'cleanest_channel_desc': 'هذه هي أنظف قناة لجهاز الراوتر الخاص بك.',
    'apply_to_router': 'تطبيق على الراوتر',
    'analyzing': 'جاري التحليل...',
    'spectrum_tips': 'نصائح الطيف',
    'tip_1': 'القنوات 1 و 6 و 11 هي القنوات الوحيدة غير المتداخلة في تردد 2.4 جيجاهرتز.',
    'tip_2': 'يمكن لأجهزة الميكروويف والبلوتوث أن تسبب تداخلاً في القناة 6.',
    'help_dashboard_1': 'التحميل/الرفع: يعرض السرعة الحالية المحدثة كل 500 مللي ثانية.',
    'help_dashboard_2': 'إجمالي الاستهلاك: يتتبع البيانات المستهلكة منذ بدء التطبيق.',
    'help_dashboard_3': 'مؤقت الجلسة: يعرض مدة المراقبة الحالية.',
    'help_dashboard_4': 'تنبيه الحصة: يتحول للون الأحمر عند تجاوز حد البيانات المحدد.',
    'help_optimizer_1': 'فحص الطيف: يحلل جميع القنوات الـ 11 بحثاً عن التداخل.',
    'help_optimizer_2': 'القناة الموصى بها: يبرز أنظف قناة باللون الأخضر.',
    'help_optimizer_3': 'تطبيق على الراوتر: يقوم بتحديث إعدادات الراوتر لأفضل قناة.',
    'help_optimizer_4': 'نصيحة: القنوات 1 و 6 و 11 هي الأفضل لشبكات 2.4 جيجاهرتز.',
    'help_security_1': 'AES-256: يتم تشفير جميع كلمات مرور الراوتر محلياً.',
    'help_security_2': 'كشف Hydra: يحظر محاولات تسجيل الدخول الفاشلة المتكررة.',
    'help_security_3': 'درع MITM: يتحقق من هوية الراوتر لمنع الانتحال.',
    'help_security_4': 'وضع الخصوصية: يعطل لقطات الشاشة ونسخ النصوص.',
    'help_conn_1': 'عنوان الراوتر: أدخل عنوان IP الخاص ببوابتك (مثلاً 192.168.1.1).',
    'help_conn_2': 'SSH (Paramiko): الاتصال عبر واجهة الأوامر للتحكم العميق.',
    'help_conn_3': 'API (Requests): الاتصال عبر واجهة برمجة التطبيقات لاسترجاع البيانات بسرعة.',
    'help_conn_4': 'WEB (Selenium): الاتصال عبر كشط واجهة الويب لأجهزة الراوتر القديمة.',
    'help_analytics_1': 'النطاق الزمني: التبديل بين العرض اليومي والأسبوعي والشهري.',
    'help_analytics_2': 'استهلاك التطبيقات: معرفة التطبيقات (YouTube، Netflix، إلخ) الأكثر استهلاكاً.',
    'help_analytics_3': 'أنواع المحتوى: عرض توزيع الفيديو، التواصل الاجتماعي، الألعاب، والعمل.',
    'help_analytics_4': 'السجل: رسوم بيانية تفاعلية تعرض أنماط الاستهلاك بمرور الوقت.',
    'help_devices_1': 'تفاصيل الجهاز: انقر فوق أي جهاز لرؤية استهلاك التطبيقات والسجل الخاص به.',
    'help_devices_2': 'حظر/إلغاء الحظر: قطع الإنترنت فوراً عن أي جهاز.',
    'help_devices_3': 'إعادة التسمية: إعطاء الأجهزة أسماء مألوفة (مثلاً "هاتف والدي").',
    'help_devices_4': 'قوة الإشارة: معرفة مدى بعد الجهاز عن الراوتر.',
    'help_dns_1': 'DNS الأساسي: الخادم الرئيسي المستخدم لتحليل النطاقات.',
    'help_dns_2': 'DNS الثانوي: خادم احتياطي في حال فشل الأساسي.',
    'help_dns_3': 'DNS مخصص: استخدام مزودين مثل Google (8.8.8.8) أو Cloudflare (1.1.1.1).',
    'help_dns_4': 'DNS حظر الإعلانات: استخدام AdGuard لحظر الإعلانات على مستوى الشبكة.',
    'help_ai_1': 'الإنجليزية/العربية: التبديل بين اللغات فوراً.',
    'help_ai_2': 'مدعوم بالذكاء الاصطناعي: يستخدم Gemini AI للترجمات السياقية.',
    'help_ai_3': 'دعم RTL: دعم كامل للتخطيط من اليمين إلى اليسار في اللغة العربية.',
    'help_ai_4': 'حفظ تلقائي: يتم حفظ تفضيلات اللغة الخاصة بك محلياً.',
    'consumption_history': 'سجل الاستهلاك',
    'daily': 'يومي',
    'usage_by_application': 'الاستهلاك حسب التطبيق',
    'content_distribution': 'توزيع المحتوى',
    'device_control': 'التحكم في الجهاز',
    'unblock_device': 'إلغاء حظر الجهاز',
    'block_device': 'حظر الجهاز',
    'limit_usage': 'تحديد الاستهلاك',
    'profile_placeholder': 'راوتر المنزل، المكتب، إلخ.',
    'pass_placeholder': 'كلمة مرور مسؤول الراوتر',
    'auto_detect': 'كشف تلقائي',
    'saving': 'جاري الحفظ...',
    'scanning': 'جاري الفحص...',
    'optimizer_desc': 'فحص وتبديل تلقائي إلى قناة الواي فاي الأقل ازدحاماً.',
    'time_limit_desc': 'تعيين حدود زمنية للأجهزة',
    'block_restricted_desc': 'حظر المواقع المقيدة',
    'automatic': 'تلقائي',
    'manual': 'يدوي',
    'lang_change_desc': 'تغيير اللغة سيقوم بتحديث الواجهة وتحليل الذكاء الاصطناعي.',
    'language_region': 'اللغة والمنطقة',
    'security_shield_active': 'الدرع الأمني نشط',
    'threats_detected': 'تم اكتشاف تهديدات',
    'scanning_for_threats': 'جاري الفحص عن التهديدات...',
    'brute_force_detected': 'تم اكتشاف هجوم تخمين',
    'mitm_detected': 'تم اكتشاف هجوم انتحال',
    'evil_twin_detected': 'تم اكتشاف شبكة وهمية',
    'speed_test_result': 'نتيجة اختبار السرعة',
    'ping': 'بينج',
    'ms': 'مللي ثانية',
    'mbps': 'ميجابت/ث',
    'auto_detect_success': 'تم التعرف على الراوتر بنجاح',
    'auto_detect_failed': 'فشل التعرف التلقائي'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('netguard_lang');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('netguard_lang', language);
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const translateText = async (text: string): Promise<string> => {
    return await geminiService.translate(text, language);
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, translateText, isRTL }}>
      <div dir={isRTL ? 'rtl' : 'ltr'} className={isRTL ? 'font-arabic' : ''}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};
