import React, { createContext, useContext, useState, useEffect } from 'react';
import { geminiService } from '../services/geminiService';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  translateText: (text: string) => Promise<string>;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'dashboard': 'Dashboard',
    'devices': 'Devices',
    'analytics': 'Analytics',
    'optimizer': 'Optimizer',
    'profiles': 'Profiles',
    'settings': 'Settings',
    'help': 'Help Center',
    'logout': 'Logout',
    'network_overview': 'Network Overview',
    'real_time_status': 'Real-time status of your NetGuard Pro router',
    'reboot_router': 'Reboot Router',
    'system_online': 'System Online',
    'download': 'Download',
    'upload': 'Upload',
    'active': 'Active',
    'uptime': 'Uptime',
    'current_speed': 'Current speed',
    'connected_now': 'Connected now',
    'system_stability': 'System stability',
    'real_time_traffic': 'Real-time Traffic',
    'system_performance': 'System Performance',
    'cpu_load': 'CPU Load',
    'ram_usage': 'RAM Usage',
    'quick_actions': 'Quick Actions',
    'guest_wifi': 'Guest Wi-Fi',
    'security_scan': 'Security Scan',
    'scan_complete': 'Scan Complete',
    'no_threats': 'No threats detected. Your network is secure.',
    'weekly_consumption': 'Weekly Consumption',
    'data_usage_gb': 'Data usage in GB',
    'quick_stats': 'Quick Stats',
    'total_download': 'Total Download',
    'total_upload': 'Total Upload',
    'peak_usage': 'Peak Usage',
    'network_health': 'Network Health',
    'connection_logs': 'Connection Logs',
    'recent_events': 'Recent network events',
    'router_settings': 'Router Settings',
    'configure_wifi': 'Configure your Wi-Fi and network security parameters',
    'wifi_config': 'Wi-Fi Configuration',
    'ssid': 'SSID (Network Name)',
    'security_mode': 'Security Mode',
    'wifi_password': 'Wi-Fi Password',
    'save_changes': 'Save Changes',
    'guest_network': 'Guest Network',
    'enable_guest': 'Enable Guest Wi-Fi',
    'guest_ssid': 'Guest SSID',
    'network_optimization': 'Network Optimization',
    'channel_optimizer': 'Channel Optimizer',
    'current_channel': 'Current Channel',
    'optimize_now': 'Optimize Now',
    'parental_controls': 'Parental Controls',
    'access_schedule': 'Access Schedule',
    'content_filter': 'Content Filter',
    'dns_settings': 'DNS Settings',
    'primary_dns': 'Primary DNS',
    'secondary_dns': 'Secondary DNS',
    'custom_dns': 'Custom DNS',
    'usage_by_app': 'Usage by Application',
    'usage_by_content': 'Usage by Content Type',
    'month': 'Month',
    'week': 'Week',
    'day': 'Day',
    'timeline': 'Timeline',
    'app_consumption': 'App Consumption',
    'device_consumption': 'Device Consumption',
    'device_management': 'Device Management',
    'manage_secure_devices': 'Manage and secure {count} devices on your network',
    'search_placeholder': 'Search by name or IP...',
    'export': 'Export',
    'total': 'Total',
    'online': 'Online',
    'offline': 'Offline',
    'all_devices': 'All Devices',
    'unblock_all': 'Unblock All',
    'device': 'Device',
    'status': 'Status',
    'signal': 'Signal',
    'ip_mac': 'IP / MAC Address',
    'speed': 'Speed',
    'actions': 'Actions',
    'unblock': 'Unblock',
    'block': 'Block',
    'no_devices_found': 'No devices found',
    'no_blocked_devices': "Great! You haven't blocked any devices yet.",
    'try_searching_different': 'Try searching for a different name or IP address.',
    'help_center': 'Help Center',
    'how_can_we_help': 'How can we help you today?',
    'back_to_topics': 'Back to Topics',
    'search_help_placeholder': 'Search for a feature or issue...',
    'still_need_help': 'Still need help?',
    'contact_support': 'Contact Support',
    'dashboard_overview': 'Dashboard Overview',
    'understand_stats': 'Understand your real-time network statistics.',
    'wifi_optimizer': 'Wi-Fi Optimizer',
    'improve_signal': 'How to improve your Wi-Fi signal stability.',
    'security_shield': 'Security Shield',
    'learn_protection': 'Learn about the military-grade protection.',
    'control_access': 'Control who accesses your network.',
    'configure_dns_help': 'Configure custom DNS servers for your network.',
    'ai_translation': 'AI Translation',
    'ai_translation_help': 'Learn how AI helps translate the app.',
    'advanced_analytics': 'Advanced Analytics',
    'router_connectivity': 'Router Connectivity',
    'router_connectivity_help': 'Connect to your router using different protocols.',
    'detailed_consumption_help': 'Track detailed consumption history and app usage.',
    'mobile_data': 'Mobile Data',
    'cellular': 'Cellular',
    'wifi': 'Wi-Fi',
    'connection_type': 'Connection Type',
    'data_plan': 'Data Plan',
    'used': 'Used',
    'remaining': 'Remaining',
    'days_left': 'Days Left',
    'signal_strength': 'Signal Strength',
    'operator': 'Operator',
    'roaming': 'Roaming',
    'set_data_limit': 'Set Data Limit',
    'master_supervisor_mode': 'Master Supervisor Mode',
    'global_infrastructure': 'Global Network Infrastructure Overview',
    'exit_master_mode': 'Exit Master Mode',
    'total_connections': 'Total Connections',
    'unique_brands': 'Unique Brands',
    'system_status': 'System Status',
    'optimal': 'Optimal',
    'connected_router_history': 'Connected Router History',
    'verified': 'Verified',
    'total_routers': 'Total Routers',
    'active_gateway': 'Active Gateway',
    'total_traffic': 'Total Traffic',
    'session_logs': 'Session Logs',
    'entries': 'Entries',
    'live': 'Live',
    'speed_test': 'Speed Test',
    'testing': 'Testing...',
    'rebooting': 'Rebooting...',
    'back_to_login': 'Back to Login',
    'no_router_connected': 'No Router Connected',
    'connect_instruction': 'Please login with your router credentials to access the admin panel.',
    'parental_control_title': 'Parental Control & Content Filtering',
    'under_development': 'Under Development',
    'content_filtering_desc': 'Block malicious websites, adult content, and set browsing schedules for specific devices. This feature is currently being optimized for your router model.',
    'configure': 'Configure',
    'close': 'Close',
    'no_logs_found': 'No session logs found.',
    'success': 'Success',
    'secure_gateway': 'Secure Gateway Management',
    'preview_mode': 'Preview Mode: Use',
    'connection_protocol': 'Connection Protocol',
    'router_address': 'Router Address',
    'username': 'Username',
    'password': 'Password',
    'remember_password': 'Remember Password',
    'forgot': 'Forgot?',
    'sign_in': 'Sign In',
    'biometric_login': 'Biometric Login',
    'ssh_desc': 'Paramiko (SSH) for CLI access',
    'api_desc': 'Requests (HTTP) for REST API',
    'web_desc': 'Selenium (Web) for scraping dashboard',
    'auth_error_auth': 'Failed to authorize with router. Check credentials.',
    'auth_error_conn': 'Failed to connect to router. Check address and network.',
    'of': 'of',
    'gb_of_gb': '{used} GB of {limit} GB',
    'download_mbps': 'Download',
    'upload_mbps': 'Upload',
    'none': 'None',
    'router_profiles': 'Router Profiles',
    'manage_gateways': 'Manage encrypted credentials for multiple gateways',
    'add_router': 'Add New Router',
    'no_profiles': 'No Profiles Saved',
    'add_first_router': 'Add your first router to start monitoring',
    'profile_name': 'Profile Name',
    'router_ip': 'Router IP',
    'save_profile': 'Save Profile',
    'cancel': 'Cancel',
    'connect_now': 'Connect Now',
    'aes_encrypted': 'AES-256 Encrypted',
    'show_password': 'Show Password',
    'hide_password': 'Hide Password',
    'discovery_mode': 'Discovery Mode',
    'searching_router': 'Searching for local router...',
    'router_found': 'Router found at {ip}',
    'router_not_found': 'No router found automatically. Please enter IP manually.',
    'operator': 'Operator',
    'signal_strength': 'Signal Strength',
    'data_plan': 'Data Plan',
    'remaining': 'Remaining',
    'roaming': 'Roaming',
    'days_left': 'Days Left',
    'dark_mode': 'Dark Mode',
    'light_mode': 'Light Mode',
    'joined': 'Joined',
    'left': 'Left',
    'blocked': 'Blocked',
    'unblocked': 'Unblocked',
    'language_region': 'Language & Region',
    'lang_change_desc': 'Changing language will update the interface and AI analysis.',
    'scanning': 'Scanning...',
    'optimizer_desc': 'Automatically scan and switch to the least congested Wi-Fi channel.',
    'set_data_limit': 'Set Data Limit',
    'time_limit_desc': 'Set time limits for devices',
    'block_restricted_desc': 'Block restricted websites',
    'automatic': 'Automatic',
    'manual': 'Manual',
    'saving': 'Saving...',
    'wifi_optimizer': 'Wi-Fi Optimizer',
    'optimizer_subtitle': 'Analyze and reduce network congestion',
    'scanning_spectrum': 'Scanning Spectrum...',
    'rescan_channels': 'Rescan Channels',
    'channel_interference': 'Channel Interference',
    'recommended': 'Recommended',
    'normal': 'Normal',
    'congested': 'Congested',
    'optimization_result': 'Optimization Result',
    'cleanest_channel_desc': 'This is the cleanest channel for your router.',
    'apply_to_router': 'Apply to Router',
    'analyzing': 'Analyzing...',
    'spectrum_tips': 'Spectrum Tips',
    'tip_1': 'Channels 1, 6, and 11 are the only non-overlapping channels in 2.4GHz.',
    'tip_2': 'Microwaves and Bluetooth devices can cause interference on channel 6.',
    'dashboard_overview': 'Dashboard Overview',
    'understand_stats': 'Understand your network statistics',
    'improve_signal': 'Improve your Wi-Fi signal quality',
    'security_shield': 'Security Shield',
    'learn_protection': 'Learn about our protection layers',
    'router_connectivity': 'Router Connectivity',
    'router_connectivity_help': 'How to connect to different routers',
    'advanced_analytics': 'Advanced Analytics',
    'detailed_consumption_help': 'Detailed data consumption analysis',
    'control_access': 'Control device access and limits',
    'configure_dns_help': 'Configure custom DNS servers',
    'ai_translation': 'AI Translation',
    'ai_translation_help': 'Multi-language support with AI',
    'search_help_placeholder': 'Search help topics...',
    'back_to_topics': 'Back to Topics',
    'still_need_help': 'Still need help?',
    'contact_support': 'Contact Support',
    'download_mbps': 'Download Speed',
    'upload_mbps': 'Upload Speed',
    'current_speed': 'Current Speed',
    'connected_now': 'Connected Now',
    'system_stability': 'System Stability',
    'cpu_load': 'CPU Load',
    'ram_usage': 'RAM Usage',
    'guest_wifi': 'Guest Wi-Fi',
    'confirm_reboot': 'Are you sure you want to reboot the router? This will temporarily disconnect all devices.',
    'no_logs_found': 'No logs found for this session.',
    'success': 'Success',
    'close': 'Close',
    'testing': 'Testing...',
    'rebooting': 'Rebooting...',
    'manage_secure_devices': 'Managing {count} secure devices on your network',
    'search_placeholder': 'Search by name or IP...',
    'total': 'Total',
    'online': 'Online',
    'offline': 'Offline',
    'all_devices': 'All Devices',
    'unblock_all': 'Unblock All',
    'ip_mac': 'IP / MAC Address',
    'unblock': 'Unblock',
    'block': 'Block',
    'no_devices_found': 'No devices found',
    'no_blocked_devices': 'You haven\'t blocked any devices yet.',
    'try_searching_different': 'Try searching for a different name or IP address.',
    'consumption_history': 'Consumption History',
    'daily': 'Daily',
    'usage_by_application': 'Usage by Application',
    'content_distribution': 'Content Distribution',
    'device_control': 'Device Control',
    'unblock_device': 'Unblock Device',
    'block_device': 'Block Device',
    'limit_usage': 'Limit Usage',
    'data_usage_gb': 'Data Usage (GB)',
    'gb_of_gb': '{used} GB of {limit} GB used',
    'total_download': 'Total Download',
    'total_upload': 'Total Upload',
    'usage_by_app': 'Usage by Application',
    'dashboard_overview': 'Dashboard Overview',
    'understand_stats': 'Understand your network statistics and performance',
    'help_dashboard_1': 'Real-time monitoring of download and upload speeds.',
    'help_dashboard_2': 'Track active devices and system uptime.',
    'help_dashboard_3': 'Manage router power and performance settings.',
    'help_dashboard_4': 'Access session logs and administrative controls.',
    'wifi_optimizer': 'Wi-Fi Optimizer',
    'improve_signal': 'Improve your signal strength and reduce interference',
    'help_optimizer_1': 'Scan for the best Wi-Fi channels in your area.',
    'help_optimizer_2': 'Reduce interference from neighboring networks.',
    'help_optimizer_3': 'Automatically switch to less congested channels.',
    'help_optimizer_4': 'Monitor signal quality over time.',
    'security_shield': 'Security Shield',
    'learn_protection': 'Learn how NetGuard Pro protects your network',
    'help_security_1': 'Advanced firewall and intrusion detection.',
    'help_security_2': 'Real-time blocking of malicious websites.',
    'help_security_3': 'Secure encrypted connections for all devices.',
    'help_security_4': 'Regular security audits and updates.',
    'router_connectivity': 'Router Connectivity',
    'router_connectivity_help': 'Troubleshoot and manage your router connection',
    'help_conn_1': 'Check physical cable and wireless connections.',
    'help_conn_2': 'Verify ISP settings and internet status.',
    'help_conn_3': 'Manage multiple router profiles easily.',
    'help_conn_4': 'Reset connection settings if needed.',
    'advanced_analytics': 'Advanced Analytics',
    'detailed_consumption_help': 'Get detailed insights into your data consumption',
    'help_analytics_1': 'Track data usage by application and device.',
    'help_analytics_2': 'Identify high-bandwidth activities.',
    'help_analytics_3': 'View historical usage trends and patterns.',
    'help_analytics_4': 'Export analytics data for further review.',
    'control_access': 'Control device access and permissions',
    'help_devices_1': 'Block or unblock devices with one tap.',
    'help_devices_2': 'Set usage limits for specific devices.',
    'help_devices_3': 'Rename and categorize your devices.',
    'help_devices_4': 'Monitor device-specific data consumption.',
    'configure_dns_help': 'Configure DNS settings for faster browsing',
    'help_dns_1': 'Choose from popular DNS providers.',
    'help_dns_2': 'Set custom DNS servers for your network.',
    'help_dns_3': 'Improve privacy and browsing speed.',
    'help_dns_4': 'Enable DNS-over-HTTPS for extra security.',
    'ai_translation': 'AI Translation',
    'ai_translation_help': 'Real-time language translation features',
    'help_ai_1': 'Switch between multiple supported languages.',
    'help_ai_2': 'Automatic translation of system messages.',
    'help_ai_3': 'Right-to-Left (RTL) support for Arabic.',
    'help_ai_4': 'Continuous improvement of translation accuracy.',
    'help_center': 'Help Center',
    'how_can_we_help': 'How can we help you today?',
    'back_to_topics': 'Back to Topics',
    'search_help_placeholder': 'Search for help topics...',
    'still_need_help': 'Still need help?',
    'contact_support': 'Contact Support',
    'timeline': 'Timeline',
    'quick_stats': 'Quick Stats',
    'peak_usage': 'Peak Usage',
    'usage_by_content': 'Usage by Content',
    'device_consumption': 'Device Consumption',
    'total_traffic': 'Total Traffic',
    'connection_logs': 'Connection Logs',
    'manage_gateways': 'Manage your network gateways and router profiles',
    'add_router': 'Add Router',
    'no_profiles': 'No Profiles Found',
    'add_first_router': 'Add your first router profile to get started.',
    'hide_password': 'Hide Password',
    'show_password': 'Show Password',
    'aes_encrypted': 'AES-256 Encrypted',
    'connect_now': 'Connect Now',
    'profile_name': 'Profile Name',
    'router_ip': 'Router IP',
    'username': 'Username',
    'password': 'Password',
    'cancel': 'Cancel',
    'save_profile': 'Save Profile',
    'profile_placeholder': 'Home Router, Office, etc.',
    'pass_placeholder': 'Router Admin Password',
    'auto_detect': 'Auto-Detect',
    'help_dashboard_1': 'Download/Upload: Shows current speed updated every 500ms.',
    'help_dashboard_2': 'Total Usage: Tracks data consumed since the app started.',
    'help_dashboard_3': 'Session Timer: Displays how long you have been monitoring.',
    'help_dashboard_4': 'Quota Alert: Turns red when you exceed your set data limit.',
    'help_optimizer_1': 'Spectrum Scan: Analyzes all 11 channels for interference.',
    'help_optimizer_2': 'Recommended Channel: Highlights the cleanest channel in green.',
    'help_optimizer_3': 'Apply to Router: Updates your router settings to the best channel.',
    'help_optimizer_4': 'Tip: Channels 1, 6, and 11 are best for 2.4GHz networks.',
    'help_security_1': 'AES-256: All router passwords are encrypted locally.',
    'help_security_2': 'Hydra Detection: Blocks repeated failed login attempts.',
    'help_security_3': 'MITM Shield: Verifies router identity to prevent spoofing.',
    'help_security_4': 'Privacy Mode: Disables screenshots and text copying.',
    'help_conn_1': 'Router Address: Enter the IP address of your gateway (e.g., 192.168.1.1).',
    'help_conn_2': 'SSH (Paramiko): Connect via command-line interface for deep control.',
    'help_conn_3': 'API (Requests): Connect via router REST API for fast data retrieval.',
    'help_conn_4': 'WEB (Selenium): Connect via web interface scraping for older routers.',
    'help_analytics_1': 'Time Range: Switch between Daily, Weekly, and Monthly views.',
    'help_analytics_2': 'App Usage: See which apps (YouTube, Netflix, etc.) consume most data.',
    'help_analytics_3': 'Content Types: View distribution of Video, Social, Gaming, and Work.',
    'help_analytics_4': 'History: Interactive charts showing usage patterns over time.',
    'help_devices_1': 'Device Details: Click any device to see its specific app usage and history.',
    'help_devices_2': 'Block/Unblock: Instantly cut off internet for any device.',
    'help_devices_3': 'Rename: Give devices friendly names (e.g., "Dad\'s Phone").',
    'help_devices_4': 'Signal Strength: See how far a device is from the router.',
    'help_dns_1': 'Primary DNS: The main server used for domain resolution.',
    'help_dns_2': 'Secondary DNS: A backup server if the primary fails.',
    'help_dns_3': 'Custom DNS: Use providers like Google (8.8.8.8) or Cloudflare (1.1.1.1).',
    'help_dns_4': 'Ad-Blocking DNS: Use AdGuard to block ads at the network level.',
    'help_ai_1': 'English/Arabic: Switch between languages instantly.',
    'help_ai_2': 'AI Powered: Uses Gemini AI for contextual translations.',
    'help_ai_3': 'RTL Support: Full support for Right-to-Left layouts in Arabic.',
    'help_ai_4': 'Auto-Save: Your language preference is saved locally.'
  },
  ar: {
    'master_supervisor_mode': 'وضع المشرف الرئيسي',
    'global_infrastructure': 'نظرة عامة على البنية التحتية العالمية للشبكة',
    'exit_master_mode': 'الخروج من وضع المشرف',
    'total_connections': 'إجمالي الاتصالات',
    'unique_brands': 'العلامات التجارية الفريدة',
    'system_status': 'حالة النظام',
    'optimal': 'مثالي',
    'connected_router_history': 'سجل أجهزة الراوتر المتصلة',
    'verified': 'تم التحقق',
    'total_routers': 'إجمالي أجهزة الراوتر',
    'active_gateway': 'البوابة النشطة',
    'total_traffic': 'إجمالي حركة المرور',
    'session_logs': 'سجلات الجلسة',
    'entries': 'مدخلات',
    'live': 'مباشر',
    'real_time_status': 'حالة الشبكة في الوقت الفعلي',
    'testing': 'جاري الاختبار...',
    'rebooting': 'جاري إعادة التشغيل...',
    'reboot_router': 'إعادة تشغيل الراوتر',
    'download_mbps': 'سرعة التحميل (Mbps)',
    'upload_mbps': 'سرعة الرفع (Mbps)',
    'current_speed': 'السرعة الحالية',
    'connected_now': 'متصل الآن',
    'system_stability': 'استقرار النظام',
    'real_time_traffic': 'حركة المرور في الوقت الفعلي',
    'system_performance': 'أداء النظام',
    'cpu_load': 'حمولة المعالج',
    'ram_usage': 'استهلاك الذاكرة',
    'guest_wifi': 'واي فاي الضيوف',
    'parental_control_title': 'الرقابة الأبوية',
    'content_filter': 'تصفية المحتوى',
    'under_development': 'قيد التطوير',
    'content_filtering_desc': 'حظر المواقع غير المرغوب فيها وجدولة الوصول للإنترنت.',
    'configure': 'إعداد',
    'no_logs_found': 'لم يتم العثور على سجلات',
    'success': 'نجاح',
    'close': 'إغلاق',
    'confirm_reboot': 'هل أنت متأكد من رغبتك في إعادة تشغيل الراوتر؟ قد ينقطع الاتصال لفترة وجيزة.',
    'usage_by_app': 'الاستهلاك حسب التطبيق',
    'device_consumption': 'استهلاك الأجهزة',
    'usage_by_content': 'الاستهلاك حسب نوع المحتوى',
    'quick_stats': 'إحصائيات سريعة',
    'total_download': 'إجمالي التحميل',
    'total_upload': 'إجمالي الرفع',
    'peak_usage': 'ذروة الاستهلاك',
    'timeline': 'الخط الزمني',
    'data_usage_gb': 'استهلاك البيانات (جيجابايت)',
    'device_management': 'إدارة الأجهزة',
    'manage_secure_devices': 'إدارة {count} أجهزة مؤمنة في شبكتك',
    'search_placeholder': 'البحث عن جهاز بالاسم أو IP...',
    'export': 'تصدير البيانات',
    'all_devices': 'كل الأجهزة',
    'unblock_all': 'إلغاء حظر الكل',
    'device': 'الجهاز',
    'status': 'الحالة',
    'signal': 'الإشارة',
    'ip_mac': 'IP / MAC',
    'speed': 'السرعة',
    'actions': 'الإجراءات',
    'unblock': 'إلغاء الحظر',
    'block': 'حظر',
    'no_devices_found': 'لم يتم العثور على أجهزة',
    'no_blocked_devices': 'لا توجد أجهزة محظورة حالياً',
    'try_searching_different': 'حاول البحث بكلمة مختلفة',
    'consumption_history': 'سجل الاستهلاك',
    'daily': 'يومي',
    'usage_by_application': 'الاستهلاك حسب التطبيق',
    'content_distribution': 'توزيع المحتوى',
    'device_control': 'التحكم في الجهاز',
    'limit_usage': 'تحديد الاستهلاك',
    'unblock_device': 'إلغاء حظر الجهاز',
    'block_device': 'حظر الجهاز',
    'back_to_login': 'العودة لتسجيل الدخول',
    'no_router_connected': 'لا يوجد راوتر متصل',
    'connect_instruction': 'يرجى تسجيل الدخول باستخدام بيانات اعتماد الراوتر للوصول إلى لوحة التحكم.',
    'secure_gateway': 'إدارة البوابة الآمنة',
    'preview_mode': 'وضع المعاينة: استخدم',
    'connection_protocol': 'بروتوكول الاتصال',
    'router_address': 'عنوان الراوتر',
    'username': 'اسم المستخدم',
    'password': 'كلمة المرور',
    'remember_password': 'تذكر كلمة المرور',
    'forgot': 'نسيت؟',
    'sign_in': 'تسجيل الدخول',
    'biometric_login': 'الدخول بالبصمة',
    'ssh_desc': 'Paramiko (SSH) للوصول إلى الواجهة النصية',
    'api_desc': 'Requests (HTTP) لواجهة REST API',
    'web_desc': 'Selenium (Web) لاستخراج بيانات لوحة التحكم',
    'auth_error_auth': 'فشل المصادقة مع الراوتر. تحقق من البيانات.',
    'auth_error_conn': 'فشل الاتصال بالراوتر. تحقق من العنوان والشبكة.',
    'of': 'من',
    'gb_of_gb': '{used} جيجابايت من {limit} جيجابايت',
    'none': 'لا يوجد',
    'router_profiles': 'ملفات الراوتر',
    'manage_gateways': 'إدارة بيانات الاعتماد المشفرة لعدة بوابات',
    'add_router': 'إضافة راوتر جديد',
    'no_profiles': 'لا توجد ملفات محفوظة',
    'add_first_router': 'أضف أول راوتر لبدء المراقبة',
    'profile_name': 'اسم الملف',
    'router_ip': 'IP الراوتر',
    'save_profile': 'حفظ الملف',
    'cancel': 'إلغاء',
    'connect_now': 'اتصل الآن',
    'aes_encrypted': 'تشفير AES-256',
    'show_password': 'إظهار كلمة المرور',
    'hide_password': 'إخفاء كلمة المرور',
    'discovery_mode': 'وضع الاكتشاف',
    'searching_router': 'البحث عن راوتر محلي...',
    'router_found': 'تم العثور على راوتر في {ip}',
    'router_not_found': 'لم يتم العثور على راوتر تلقائياً. يرجى إدخال IP يدوياً.',
    'ssid': 'اسم الشبكة (SSID)',
    'security_mode': 'وضع الأمان',
    'wifi_password': 'كلمة مرور الواي فاي',
    'save_changes': 'حفظ التغييرات',
    'saving': 'جاري الحفظ...',
    'dns_settings': 'إعدادات DNS',
    'automatic': 'تلقائي',
    'manual': 'يدوي',
    'primary_dns': 'DNS الأساسي',
    'secondary_dns': 'DNS الثانوي',
    'language_region': 'اللغة والمنطقة',
    'lang_change_desc': 'تغيير اللغة سيقوم بتحديث الواجهة وتحليل الذكاء الاصطناعي.',
    'network_optimization': 'تحسين الشبكة',
    'channel_optimizer': 'محسن قنوات الواي فاي',
    'optimizer_desc': 'فحص وتبديل تلقائي إلى قناة الواي فاي الأقل ازدحاماً.',
    'current_channel': 'القناة الحالية',
    'scanning': 'جاري الفحص...',
    'optimize_now': 'تحسين الآن',
    'mobile_data': 'بيانات الهاتف',
    'data_limit': 'حد البيانات',
    'renewal_date': 'تاريخ التجديد',
    'set_data_limit': 'تعيين حد البيانات',
    'parental_controls': 'الرقابة الأبوية',
    'access_schedule': 'جدول الوصول',
    'time_limit_desc': 'تعيين حدود زمنية للأجهزة',
    'content_filter': 'تصفية المحتوى',
    'block_restricted_desc': 'حظر المواقع المقيدة',
    'help_center': 'مركز المساعدة',
    'how_can_we_help': 'كيف يمكننا مساعدتك اليوم؟',
    'back_to_topics': 'العودة إلى المواضيع',
    'search_help_placeholder': 'ابحث عن ميزة أو مشكلة...',
    'still_need_help': 'هل ما زلت بحاجة للمساعدة؟',
    'contact_support': 'اتصل بالدعم',
    'dashboard_overview': 'نظرة عامة على لوحة التحكم',
    'understand_stats': 'فهم إحصائيات الشبكة في الوقت الفعلي.',
    'wifi_optimizer': 'محسن الواي فاي',
    'improve_signal': 'كيفية تحسين استقرار إشارة الواي فاي.',
    'security_shield': 'درع الأمان',
    'learn_protection': 'تعرف على الحماية العسكرية.',
    'control_access': 'التحكم في من يصل إلى شبكتك.',
    'configure_dns_help': 'تكوين خوادم DNS مخصصة لشبكتك.',
    'ai_translation': 'ترجمة الذكاء الاصطناعي',
    'ai_translation_help': 'تعرف على كيفية مساعدة الذكاء الاصطناعي في ترجمة التطبيق.',
    'advanced_analytics': 'التحليلات المتقدمة',
    'router_connectivity': 'اتصال الراوتر',
    'router_connectivity_help': 'الاتصال بالراوتر باستخدام بروتوكولات مختلفة.',
    'detailed_consumption_help': 'تتبع سجل الاستهلاك التفصيلي واستخدام التطبيقات.',
    'mobile_data': 'بيانات الجوال',
    'cellular': 'خلوي',
    'wifi': 'واي فاي',
    'connection_type': 'نوع الاتصال',
    'data_plan': 'باقة البيانات',
    'used': 'مستخدم',
    'remaining': 'متبقي',
    'days_left': 'أيام متبقية',
    'signal_strength': 'قوة الإشارة',
    'operator': 'المشغل',
    'roaming': 'تجوال',
    'set_data_limit': 'تعيين حد البيانات',
    'master_supervisor_mode': 'وضع المشرف الرئيسي',
    'global_infrastructure': 'نظرة عامة على البنية التحتية العالمية للشبكة',
    'exit_master_mode': 'الخروج من الوضع الرئيسي',
    'total_connections': 'إجمالي الاتصالات',
    'unique_brands': 'العلامات التجارية الفريدة',
    'system_status': 'حالة النظام',
    'optimal': 'مثالي',
    'connected_router_history': 'سجل أجهزة الراوتر المتصلة',
    'verified': 'تم التحقق',
    'total_routers': 'إجمالي أجهزة الراوتر',
    'active_gateway': 'البوابة النشطة',
    'total_traffic': 'إجمالي حركة المرور',
    'session_logs': 'سجلات الجلسات',
    'entries': 'مدخلات',
    'live': 'مباشر',
    'speed_test': 'اختبار السرعة',
    'testing': 'جاري الاختبار...',
    'rebooting': 'جاري إعادة التشغيل...',
    'back_to_login': 'العودة لتسجيل الدخول',
    'no_router_connected': 'لا يوجد راوتر متصل',
    'connect_instruction': 'يرجى تسجيل الدخول باستخدام بيانات اعتماد الراوتر للوصول إلى لوحة الإدارة.',
    'parental_control_title': 'الرقابة الأبوية وتصفية المحتوى',
    'under_development': 'قيد التطوير',
    'content_filtering_desc': 'حظر المواقع الضارة، المحتوى البالغ، وتعيين جداول التصفح لأجهزة محددة. هذه الميزة قيد التحسين حالياً لموديل الراوتر الخاص بك.',
    'configure': 'تكوين',
    'close': 'إغلاق',
    'no_logs_found': 'لم يتم العثور على سجلات جلسات.',
    'success': 'نجاح',
    'secure_gateway': 'إدارة البوابة الآمنة',
    'preview_mode': 'وضع المعاينة: استخدم',
    'connection_protocol': 'بروتوكول الاتصال',
    'router_address': 'عنوان الراوتر',
    'username': 'اسم المستخدم',
    'password': 'كلمة المرور',
    'remember_password': 'تذكر كلمة المرور',
    'forgot': 'نسيت؟',
    'sign_in': 'تسجيل الدخول',
    'biometric_login': 'الدخول بالبصمة',
    'ssh_desc': 'Paramiko (SSH) للوصول إلى واجهة الأوامر',
    'api_desc': 'Requests (HTTP) لواجهة برمجة التطبيقات REST',
    'web_desc': 'Selenium (Web) لكشط لوحة التحكم',
    'auth_error_auth': 'فشل التفويض مع الراوتر. تحقق من البيانات.',
    'auth_error_conn': 'فشل الاتصال بالراوتر. تحقق من العنوان والشبكة.',
    'of': 'من',
    'gb_of_gb': '{used} جيجابايت من {limit} جيجابايت',
    'download_mbps': 'تحميل',
    'upload_mbps': 'رفع',
    'none': 'لا يوجد',
    'router_profiles': 'ملفات الراوتر',
    'manage_gateways': 'إدارة بيانات الاعتماد المشفرة لعدة بوابات',
    'add_router': 'إضافة راوتر جديد',
    'no_profiles': 'لا توجد ملفات محفوظة',
    'add_first_router': 'أضف أول راوتر لبدء المراقبة',
    'profile_name': 'اسم الملف الشخصي',
    'router_ip': 'عنوان IP للراوتر',
    'save_profile': 'حفظ الملف الشخصي',
    'cancel': 'إلغاء',
    'connect_now': 'اتصل الآن',
    'aes_encrypted': 'مشفر بـ AES-256',
    'show_password': 'إظهار كلمة المرور',
    'hide_password': 'إخفاء كلمة المرور',
    'discovery_mode': 'وضع الاكتشاف',
    'searching_router': 'البحث عن الراوتر المحلي...',
    'router_found': 'تم العثور على راوتر في {ip}',
    'router_not_found': 'لم يتم العثور على راوتر تلقائياً. يرجى إدخال IP يدوياً.',
    'operator': 'المشغل',
    'signal_strength': 'قوة الإشارة',
    'data_plan': 'خطة البيانات',
    'remaining': 'المتبقي',
    'roaming': 'التجوال',
    'days_left': 'أيام متبقية',
    'dark_mode': 'الوضع الداكن',
    'light_mode': 'الوضع الفاتح',
    'joined': 'انضم',
    'left': 'غادر',
    'blocked': 'محظور',
    'unblocked': 'غير محظور',
    'language_region': 'اللغة والمنطقة',
    'lang_change_desc': 'تغيير اللغة سيقوم بتحديث الواجهة وتحليل الذكاء الاصطناعي.',
    'scanning': 'جاري الفحص...',
    'optimizer_desc': 'فحص وتبديل تلقائي إلى قناة الواي فاي الأقل ازدحاماً.',
    'set_data_limit': 'تعيين حد البيانات',
    'time_limit_desc': 'تعيين حدود زمنية للأجهزة',
    'block_restricted_desc': 'حظر المواقع المقيدة',
    'automatic': 'تلقائي',
    'manual': 'يدوي',
    'saving': 'جاري الحفظ...',
    'wifi_optimizer': 'محسن الواي فاي',
    'optimizer_subtitle': 'تحليل وتقليل ازدحام الشبكة',
    'scanning_spectrum': 'جاري فحص الطيف...',
    'rescan_channels': 'إعادة فحص القنوات',
    'channel_interference': 'تداخل القنوات',
    'recommended': 'موصى به',
    'normal': 'عادي',
    'congested': 'مزدحم',
    'optimization_result': 'نتيجة التحسين',
    'cleanest_channel_desc': 'هذه هي أنظف قناة لجهاز الراوتر الخاص بك.',
    'apply_to_router': 'تطبيق على الراوتر',
    'analyzing': 'جاري التحليل...',
    'spectrum_tips': 'نصائح الطيف',
    'tip_1': 'القنوات 1 و 6 و 11 هي القنوات الوحيدة غير المتداخلة في تردد 2.4 جيجاهرتز.',
    'tip_2': 'يمكن لأجهزة الميكروويف والبلوتوث أن تسبب تداخلاً في القناة 6.',
    'dashboard_overview': 'نظرة عامة على لوحة التحكم',
    'understand_stats': 'فهم إحصائيات شبكتك',
    'improve_signal': 'تحسين جودة إشارة الواي فاي',
    'security_shield': 'درع الحماية',
    'learn_protection': 'تعرف على طبقات الحماية لدينا',
    'router_connectivity': 'اتصال الراوتر',
    'router_connectivity_help': 'كيفية الاتصال بأنواع مختلفة من أجهزة الراوتر',
    'advanced_analytics': 'تحليلات متقدمة',
    'detailed_consumption_help': 'تحليل مفصل لاستهلاك البيانات',
    'control_access': 'التحكم في وصول الأجهزة والحدود',
    'configure_dns_help': 'تكوين خوادم DNS مخصصة',
    'ai_translation': 'ترجمة الذكاء الاصطناعي',
    'ai_translation_help': 'دعم لغات متعددة باستخدام الذكاء الاصطناعي',
    'search_help_placeholder': 'البحث في مواضيع المساعدة...',
    'back_to_topics': 'العودة إلى المواضيع',
    'still_need_help': 'هل ما زلت بحاجة للمساعدة؟',
    'contact_support': 'اتصل بالدعم',
    'download_mbps': 'سرعة التحميل',
    'upload_mbps': 'سرعة الرفع',
    'current_speed': 'السرعة الحالية',
    'connected_now': 'متصل الآن',
    'system_stability': 'استقرار النظام',
    'cpu_load': 'حمل المعالج',
    'ram_usage': 'استهلاك الرام',
    'guest_wifi': 'واي فاي الضيوف',
    'confirm_reboot': 'هل أنت متأكد أنك تريد إعادة تشغيل الراوتر؟ سيؤدي ذلك إلى قطع اتصال جميع الأجهزة مؤقتاً.',
    'no_logs_found': 'لم يتم العثور على سجلات لهذه الجلسة.',
    'success': 'نجاح',
    'close': 'إغلاق',
    'testing': 'جاري الاختبار...',
    'rebooting': 'جاري إعادة التشغيل...',
    'manage_secure_devices': 'إدارة {count} أجهزة آمنة على شبكتك',
    'search_placeholder': 'البحث بالاسم أو عنوان IP...',
    'total': 'الإجمالي',
    'online': 'متصل',
    'offline': 'غير متصل',
    'all_devices': 'جميع الأجهزة',
    'unblock_all': 'إلغاء حظر الكل',
    'ip_mac': 'عنوان IP / MAC',
    'unblock': 'إلغاء الحظر',
    'block': 'حظر',
    'no_devices_found': 'لم يتم العثور على أجهزة',
    'no_blocked_devices': 'لم تقم بحظر أي أجهزة بعد.',
    'try_searching_different': 'حاول البحث عن اسم أو عنوان IP مختلف.',
    'consumption_history': 'سجل الاستهلاك',
    'daily': 'يومي',
    'usage_by_application': 'الاستهلاك حسب التطبيق',
    'content_distribution': 'توزيع المحتوى',
    'device_control': 'التحكم في الجهاز',
    'unblock_device': 'إلغاء حظر الجهاز',
    'block_device': 'حظر الجهاز',
    'limit_usage': 'تحديد الاستهلاك',
    'data_usage_gb': 'استهلاك البيانات (جيجابايت)',
    'gb_of_gb': 'تم استهلاك {used} جيجابايت من أصل {limit} جيجابايت',
    'total_download': 'إجمالي التحميل',
    'total_upload': 'إجمالي الرفع',
    'usage_by_app': 'الاستهلاك حسب التطبيق',
    'dashboard_overview': 'نظرة عامة على لوحة التحكم',
    'understand_stats': 'فهم إحصائيات وأداء شبكتك',
    'help_dashboard_1': 'مراقبة فورية لسرعات التحميل والرفع.',
    'help_dashboard_2': 'تتبع الأجهزة النشطة ووقت تشغيل النظام.',
    'help_dashboard_3': 'إدارة طاقة الراوتر وإعدادات الأداء.',
    'help_dashboard_4': 'الوصول إلى سجلات الجلسات وضوابط المسؤول.',
    'wifi_optimizer': 'محسن الواي فاي',
    'improve_signal': 'تحسين قوة الإشارة وتقليل التداخل',
    'help_optimizer_1': 'البحث عن أفضل قنوات الواي فاي في منطقتك.',
    'help_optimizer_2': 'تقليل التداخل من الشبكات المجاورة.',
    'help_optimizer_3': 'التبديل التلقائي إلى القنوات الأقل ازدحاماً.',
    'help_optimizer_4': 'مراقبة جودة الإشارة بمرور الوقت.',
    'security_shield': 'درع الحماية',
    'learn_protection': 'تعرف على كيفية حماية NetGuard Pro لشبكتك',
    'help_security_1': 'جدار حماية متقدم وكشف التسلل.',
    'help_security_2': 'حظر فوري للمواقع الإلكترونية الضارة.',
    'help_security_3': 'اتصالات مشفرة آمنة لجميع الأجهزة.',
    'help_security_4': 'عمليات تدقيق وتحديثات أمنية منتظمة.',
    'router_connectivity': 'اتصال الراوتر',
    'router_connectivity_help': 'استكشاف أخطاء اتصال الراوتر وإدارتها',
    'help_conn_1': 'التحقق من الكابلات المادية والاتصالات اللاسلكية.',
    'help_conn_2': 'التحقق من إعدادات مزود الخدمة وحالة الإنترنت.',
    'help_conn_3': 'إدارة ملفات تعريف متعددة للراوتر بسهولة.',
    'help_conn_4': 'إعادة تعيين إعدادات الاتصال إذا لزم الأمر.',
    'advanced_analytics': 'تحليلات متقدمة',
    'detailed_consumption_help': 'احصل على رؤى مفصلة حول استهلاك البيانات',
    'help_analytics_1': 'تتبع استهلاك البيانات حسب التطبيق والجهاز.',
    'help_analytics_2': 'تحديد الأنشطة التي تستهلك نطاقاً تردديًا عاليًا.',
    'help_analytics_3': 'عرض اتجاهات وأنماط الاستهلاك التاريخية.',
    'help_analytics_4': 'تصدير بيانات التحليلات لمزيد من المراجعة.',
    'control_access': 'التحكم في وصول الأجهزة والأذونات',
    'help_devices_1': 'حظر أو إلغاء حظر الأجهزة بضغطة واحدة.',
    'help_devices_2': 'تعيين حدود الاستهلاك لأجهزة محددة.',
    'help_devices_3': 'إعادة تسمية وتصنيف أجهزتك.',
    'help_devices_4': 'مراقبة استهلاك البيانات الخاص بكل جهاز.',
    'configure_dns_help': 'تكوين إعدادات DNS لتصفح أسرع',
    'help_dns_1': 'الاختيار من بين مزودي DNS المشهورين.',
    'help_dns_2': 'تعيين خوادم DNS مخصصة لشبكتك.',
    'help_dns_3': 'تحسين الخصوصية وسرعة التصفح.',
    'help_dns_4': 'تمكين DNS-over-HTTPS لمزيد من الأمان.',
    'ai_translation': 'ترجمة الذكاء الاصطناعي',
    'ai_translation_help': 'ميزات ترجمة اللغة في الوقت الفعلي',
    'help_ai_1': 'التبديل بين لغات متعددة مدعومة.',
    'help_ai_2': 'ترجمة تلقائية لرسائل النظام.',
    'help_ai_3': 'دعم الكتابة من اليمين إلى اليسار (RTL) للغة العربية.',
    'help_ai_4': 'تحسين مستمر لدقة الترجمة.',
    'help_center': 'مركز المساعدة',
    'how_can_we_help': 'كيف يمكننا مساعدتك اليوم؟',
    'back_to_topics': 'العودة إلى المواضيع',
    'search_help_placeholder': 'البحث عن مواضيع المساعدة...',
    'still_need_help': 'هل ما زلت بحاجة للمساعدة؟',
    'contact_support': 'اتصل بالدعم',
    'timeline': 'الجدول الزمني',
    'quick_stats': 'إحصائيات سريعة',
    'peak_usage': 'ذروة الاستهلاك',
    'usage_by_content': 'الاستهلاك حسب المحتوى',
    'device_consumption': 'استهلاك الأجهزة',
    'total_traffic': 'إجمالي حركة المرور',
    'connection_logs': 'سجلات الاتصال',
    'manage_gateways': 'إدارة بوابات الشبكة وملفات تعريف الراوتر',
    'add_router': 'إضافة راوتر',
    'no_profiles': 'لم يتم العثور على ملفات تعريف',
    'add_first_router': 'أضف أول ملف تعريف للراوتر للبدء.',
    'hide_password': 'إخفاء كلمة المرور',
    'show_password': 'عرض كلمة المرور',
    'aes_encrypted': 'مشفر بـ AES-256',
    'connect_now': 'اتصل الآن',
    'profile_name': 'اسم ملف التعريف',
    'router_ip': 'عنوان IP للراوتر',
    'username': 'اسم المستخدم',
    'password': 'كلمة المرور',
    'cancel': 'إلغاء',
    'save_profile': 'حفظ ملف التعريف',
    'profile_placeholder': 'راوتر المنزل، المكتب، إلخ.',
    'pass_placeholder': 'كلمة مرور مسؤول الراوتر',
    'auto_detect': 'كشف تلقائي',
    'help_dashboard_1': 'التحميل/الرفع: يعرض السرعة الحالية المحدثة كل 500 مللي ثانية.',
    'help_dashboard_2': 'إجمالي الاستهلاك: يتتبع البيانات المستهلكة منذ بدء التطبيق.',
    'help_dashboard_3': 'مؤقت الجلسة: يعرض مدة المراقبة الحالية.',
    'help_dashboard_4': 'تنبيه الحصة: يتحول للون الأحمر عند تجاوز حد البيانات المحدد.',
    'help_optimizer_1': 'فحص الطيف: يحلل جميع القنوات الـ 11 بحثاً عن التداخل.',
    'help_optimizer_2': 'القناة الموصى بها: يبرز أنظف قناة باللون الأخضر.',
    'help_optimizer_3': 'تطبيق على الراوتر: يقوم بتحديث إعدادات الراوتر لأفضل قناة.',
    'help_optimizer_4': 'نصيحة: القنوات 1 و 6 و 11 هي الأفضل لشبكات 2.4 جيجاهرتز.',
    'help_security_1': 'AES-256: يتم تشفير جميع كلمات مرور الراوتر محلياً.',
    'help_security_2': 'كشف Hydra: يحظر محاولات تسجيل الدخول الفاشلة المتكررة.',
    'help_security_3': 'درع MITM: يتحقق من هوية الراوتر لمنع الانتحال.',
    'help_security_4': 'وضع الخصوصية: يعطل لقطات الشاشة ونسخ النصوص.',
    'help_conn_1': 'عنوان الراوتر: أدخل عنوان IP الخاص ببوابتك (مثلاً 192.168.1.1).',
    'help_conn_2': 'SSH (Paramiko): الاتصال عبر واجهة الأوامر للتحكم العميق.',
    'help_conn_3': 'API (Requests): الاتصال عبر واجهة برمجة التطبيقات لاسترجاع البيانات بسرعة.',
    'help_conn_4': 'WEB (Selenium): الاتصال عبر كشط واجهة الويب لأجهزة الراوتر القديمة.',
    'help_analytics_1': 'النطاق الزمني: التبديل بين العرض اليومي والأسبوعي والشهري.',
    'help_analytics_2': 'استهلاك التطبيقات: معرفة التطبيقات (YouTube، Netflix، إلخ) الأكثر استهلاكاً.',
    'help_analytics_3': 'أنواع المحتوى: عرض توزيع الفيديو، التواصل الاجتماعي، الألعاب، والعمل.',
    'help_analytics_4': 'السجل: رسوم بيانية تفاعلية تعرض أنماط الاستهلاك بمرور الوقت.',
    'help_devices_1': 'تفاصيل الجهاز: انقر فوق أي جهاز لرؤية استهلاك التطبيقات والسجل الخاص به.',
    'help_devices_2': 'حظر/إلغاء الحظر: قطع الإنترنت فوراً عن أي جهاز.',
    'help_devices_3': 'إعادة التسمية: إعطاء الأجهزة أسماء مألوفة (مثلاً "هاتف والدي").',
    'help_devices_4': 'قوة الإشارة: معرفة مدى بعد الجهاز عن الراوتر.',
    'help_dns_1': 'DNS الأساسي: الخادم الرئيسي المستخدم لتحليل النطاقات.',
    'help_dns_2': 'DNS الثانوي: خادم احتياطي في حال فشل الأساسي.',
    'help_dns_3': 'DNS مخصص: استخدام مزودين مثل Google (8.8.8.8) أو Cloudflare (1.1.1.1).',
    'help_dns_4': 'DNS حظر الإعلانات: استخدام AdGuard لحظر الإعلانات على مستوى الشبكة.',
    'help_ai_1': 'الإنجليزية/العربية: التبديل بين اللغات فوراً.',
    'help_ai_2': 'مدعوم بالذكاء الاصطناعي: يستخدم Gemini AI للترجمات السياقية.',
    'help_ai_3': 'دعم RTL: دعم كامل للتخطيط من اليمين إلى اليسار في اللغة العربية.',
    'help_ai_4': 'حفظ تلقائي: يتم حفظ تفضيلات اللغة الخاصة بك محلياً.'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('netguard_lang');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('netguard_lang', language);
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const translateText = async (text: string): Promise<string> => {
    return await geminiService.translate(text, language);
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, translateText, isRTL }}>
      <div dir={isRTL ? 'rtl' : 'ltr'} className={isRTL ? 'font-arabic' : ''}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};
