export type Language = 'ar' | 'en';

export const TRANSLATIONS = {
  ar: {
    title: "NetGuard Pro",
    login: "تسجيل الدخول",
    dashboard: "لوحة التحكم",
    devices: "الأجهزة",
    router: "الراوتر",
    settings: "الإعدادات",
    logs: "السجلات",
    logout: "خروج",
    routerIp: "عنوان الراوتر",
    username: "اسم المستخدم",
    password: "كلمة المرور",
    rightToKnow: "حقك أن تعرف كفاءة شبكتك",
    viewSystemLogs: "عرض سجل النظام (عام)",
    connected: "متصل",
    secure: "النظام آمن",
    protected: "محمي",
    highPrecision: "دقة عالية",
    loading: "جاري التحميل...",
    optimize: "تحسين",
    scan: "فحص",
    connectedDevices: "الأجهزة المتصلة",
    totalUsage: "إجمالي الاستهلاك",
    appUsage: "استهلاك التطبيقات",
    streaming: "البث",
    browsing: "التصفح",
    cloud: "السحابة",
    appStore: "المتجر",
    download: "تحميل",
    upload: "رفع",
    networkOverview: "نظرة عامة",
    buildHistory: "سجل عمليات البناء",
    build_logs: "سجلات النظام",
    liveAudit: "تدقيق حي",
    diagnosticMode: "وضع التشخيص",
    lastBuild: "آخر بناء",
    status: "الحالة",
    description: "الوصف",
    language: "اللغة",
    theme: "المظهر (فاتح/داكن)",
    security: "الأمان",
    changePass: "تغيير كلمة المرور",
    save: "حفظ الإعدادات",
    wifiSettings: "إعدادات الواي فاي",
    ssid: "اسم الشبكة",
    wifiPass: "كلمة سر الواي فاي",
    hideSsid: "إخفاء الشبكة",
    speedLimit: "تحديد السرعة",
    unlimited: "غير محدود",
    mb5: "5 ميجا",
    mb10: "10 ميجا",
    block: "حظر",
    blacklist: "قائمة الحظر",
    unblock: "إلغاء الحظر",
    reboot: "إعادة تشغيل",
    reset: "ضبط المصنع",
    wifiOff: "إيقاف الواي فاي",
    snr: "جودة الخط (SNR)",
    lineStability: "استقرار الخط",
    remainingData: "الباقة المتبقية",
    renewalDate: "تاريخ التجديد",
    signalStats: "إحصائيات الإشارة",
    hardwareControl: "التحكم في العتاد",
    caution: "تنبيه: كن حذراً عند استخدام هذه العمليات"
  },
  en: {
    title: "NetGuard Pro",
    login: "Sign In",
    dashboard: "Dashboard",
    devices: "Devices",
    router: "Router",
    settings: "Settings",
    logs: "Logs",
    logout: "Logout",
    routerIp: "Router IP",
    username: "Username",
    password: "Password",
    rightToKnow: "Your right to know your network efficiency",
    viewSystemLogs: "View System Logs (Public)",
    connected: "Connected",
    secure: "System Secure",
    protected: "Protected",
    highPrecision: "High Precision",
    loading: "Loading...",
    optimize: "Optimize",
    scan: "Scan",
    connectedDevices: "Connected Devices",
    totalUsage: "Total Usage",
    appUsage: "App Usage",
    streaming: "Streaming",
    browsing: "Browsing",
    cloud: "Cloud",
    appStore: "App Store",
    download: "Download",
    upload: "Upload",
    networkOverview: "Network Overview",
    buildHistory: "Build Process History",
    build_logs: "System Logs",
    liveAudit: "Live Audit",
    diagnosticMode: "Diagnostic Mode",
    lastBuild: "Last Build",
    status: "Status",
    description: "Description",
    language: "Language",
    theme: "Theme (Light/Dark)",
    security: "Security",
    changePass: "Change Password",
    save: "Save Settings",
    wifiSettings: "Wi-Fi Settings",
    ssid: "Network Name (SSID)",
    wifiPass: "Wi-Fi Password",
    hideSsid: "Hide Network",
    speedLimit: "Speed Limit",
    unlimited: "Unlimited",
    mb5: "5 Mbps",
    mb10: "10 Mbps",
    block: "Block",
    blacklist: "Blacklist",
    unblock: "Unblock",
    reboot: "Reboot",
    reset: "Factory Reset",
    wifiOff: "Turn off Wi-Fi",
    snr: "Line Quality (SNR)",
    lineStability: "Line Stability",
    remainingData: "Remaining Data",
    renewalDate: "Renewal Date",
    signalStats: "Signal Statistics",
    hardwareControl: "Hardware Control",
    caution: "Caution: Use these operations with care"
  }
};
