export type Language = 'ar' | 'en';

export const TRANSLATIONS = {
  ar: {
    title: "NetGuard Pro",
    login: "تسجيل الدخول",
    dashboard: "لوحة التحكم",
    devices: "الأجهزة",
    router: "الراوتر",
    settings: "الإعدادات",
    logs: "السجلات",
    logout: "خروج",
    routerIp: "عنوان الراوتر",
    username: "اسم المستخدم",
    password: "كلمة المرور",
    rightToKnow: "حقك أن تعرف كفاءة شبكتك",
    viewSystemLogs: "عرض سجل النظام (عام)",
    connected: "متصل",
    secure: "النظام آمن",
    protected: "محمي",
    highPrecision: "دقة عالية",
    loading: "جاري التحميل...",
    optimize: "تحسين",
    scan: "فحص",
    connectedDevices: "الأجهزة المتصلة",
    totalUsage: "إجمالي الاستهلاك",
    appUsage: "استهلاك التطبيقات",
    streaming: "البث",
    browsing: "التصفح",
    cloud: "السحابة",
    appStore: "المتجر",
    download: "تحميل",
    upload: "رفع",
    networkOverview: "نظرة عامة",
    buildHistory: "سجل عمليات البناء",
    build_logs: "سجلات النظام",
    liveAudit: "تدقيق حي",
    diagnosticMode: "وضع التشخيص",
    lastBuild: "آخر بناء",
    status: "الحالة",
    description: "الوصف",
    language: "اللغة",
    theme: "المظهر (فاتح/داكن)",
    security: "الأمان",
    changePass: "تغيير كلمة المرور",
    save: "حفظ الإعدادات"
  },
  en: {
    title: "NetGuard Pro",
    login: "Sign In",
    dashboard: "Dashboard",
    devices: "Devices",
    router: "Router",
    settings: "Settings",
    logs: "Logs",
    logout: "Logout",
    routerIp: "Router IP",
    username: "Username",
    password: "Password",
    rightToKnow: "Your right to know your network efficiency",
    viewSystemLogs: "View System Logs (Public)",
    connected: "Connected",
    secure: "System Secure",
    protected: "Protected",
    highPrecision: "High Precision",
    loading: "Loading...",
    optimize: "Optimize",
    scan: "Scan",
    connectedDevices: "Connected Devices",
    totalUsage: "Total Usage",
    appUsage: "App Usage",
    streaming: "Streaming",
    browsing: "Browsing",
    cloud: "Cloud",
    appStore: "App Store",
    download: "Download",
    upload: "Upload",
    networkOverview: "Network Overview",
    buildHistory: "Build Process History",
    build_logs: "System Logs",
    liveAudit: "Live Audit",
    diagnosticMode: "Diagnostic Mode",
    lastBuild: "Last Build",
    status: "Status",
    description: "Description",
    language: "Language",
    theme: "Theme (Light/Dark)",
    security: "Security",
    changePass: "Change Password",
    save: "Save Settings"
  }
};
