export const TRANSLATIONS = {
  ar: {
    title: "NetGuard Pro",
    login: "تسجيل الدخول",
    dashboard: "لوحة التحكم",
    logs: "سجل الأمان",
    connected: "متصل",
    threats: "تهديدات",
    devices: "أجهزة",
    usage: "الاستهلاك",
    scan: "فحص عميق",
    optimize: "تحسين",
    secure: "النظام آمن",
    unauthorized: "محاولة اختراق",
    suspicious: "نشاط مشبوه",
    protected: "محمي بواسطة الذكاء الاصطناعي",
    history: "تاريخ النشاط",
    settings: "الإعدادات",
    logout: "خروج"
  },
  en: {
    title: "NetGuard Pro",
    login: "Login",
    dashboard: "Dashboard",
    logs: "Security Logs",
    connected: "Connected",
    threats: "Threats",
    devices: "Devices",
    usage: "Usage",
    scan: "Deep Scan",
    optimize: "Optimize",
    secure: "System Secure",
    unauthorized: "Intrusion Attempt",
    suspicious: "Suspicious Activity",
    protected: "AI Protected",
    history: "Activity History",
    settings: "Settings",
    logout: "Logout"
  }
};
